### ISSUE TITLE
hangs when entering large collection

### ISSUE THREAD

**Issue by MartinLoeper** [kopecmaciej/vi-mongo#62]
First of all: Thanks for this wonderful tool!

I have one issue which is a real blocker to make it my daily driver right now:

When I press enter on a large collection with multiple millions of documents, the applications freezes and nothing happens.
I guess it runs some command on that large collection which is preventing it from displaying anything.

Could you guide me how to figure out what is going on?

**Comment by kopecmaciej** [comment]
Hello @MartinLoeper, so after clicking enter on collection couple things are happening:
1. Count document query - this is applied with filter so it's not as fast as `estimatedDocumentCount()` but should be fairly quick 
2. Find query - this is also applied with filter so `query filter`, `limit`, `sort` `projection` etc. This really depends on how the db is build, if there are no indexes this could take very long time
3. Get indexes - this should be the fastest as it's only getting index lists and metadata about them, so number of documents is irrelevant here

There is a way to set hard coded limit in configuration, but I'm not sure this would help you.
```
connections:
  - name: "local"
    url: "mongodb://localhost:27017"
    host: "localhost"
    port: 27017
    database: "test"
    username: ""
    password: ""
    timeout: 10
    options:
      limit: 20
```
If you're working with this collection for e.g. via shell, is everything much faster?
