### ISSUE TITLE
Feature request: Reference envs on config

### ISSUE THREAD

**Issue by thisago** [kopecmaciej/vi-mongo#82]
Instead of saving the secrets as plain text on the YAML config file, I wanted to be able to reference them as environment variables, like this:
```yaml
connections:
    - url: $MONGODB_URI_CONN1
      name: Connection 1
      timeout: 5
      options: {}
```

Instead of now:
```yaml
connections:
    - url: mongodb://rootuser:rootpass@localhost:27017
      host: localhost
      port: 27017
      database: ""
      username: ""
      password: ""
      name: localhost
      timeout: 5
      options: {}
```

This would help to manage the configuration over devices without worrying.

Another idea is keep the connections on a separated file, to keep user preferences safe to share.
